title: Insights Content Service
description: Content Service for Openshift insights remmediations
baseurl: /content-service
url: "https://redhatinsights.github.io"
repository: "RedHatInsights/content-service"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/RedHatInsights/content-service"

footer_content: "Copyright &copy; 2020 Red Hat, Inc.</a>"

# Build settings
# markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - sources.tmpl.md

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607
