title: Insights Content Service
description: Content Service for Openshift insights remmediations
baseurl: /content-service
url: "https://ccx.pages.redhat.com"

# heading_anchors: true
# search_enabled: false

aux_links:
  "Gitlab repository":
    - "https://redhat.com/content-service"

# footer_content: "Copyright &copy; 2020 Red Hat, Inc.</a>"

# Build settings
# markdown: kramdown
theme: just-the-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - sources.tmpl.md

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607
